Working on task third
htmlacademy-javascript/1370879-code-and-magick-21 pull request #4
Opened 2020-09-25 16:11 UTC by ministrov

2020-09-28 17:48 UTC, yulllll requested changes

2020-09-28 17:48 UTC, yulllll commented on js/setup.js
> +let userDialog = document.querySelector('.setup');
везде используй для объявления переменных const, и только когда тебе нужно потом присвоить переменной какое-то новое значение, то меняй на let

2020-09-28 17:48 UTC, yulllll commented on js/setup.js
> +let similarListElement = document.querySelector('.setup-similar-list');
поиск этого элемента делай внутри userDialog, а не document - так он отработает быстрее

2020-09-28 17:48 UTC, yulllll commented on js/setup.js
> +  {name: WIZARD_NAMES[0], surname: WIZARD_SURNAME[0], colorCoat: 'rgb(241, 43, 107)', eyesColor: 'red'},
нужны выбирать рандомные элементы, а не по порядку

Из описания ДЗ:
Стоит отдельно объявить функцию генерации случайных данных

2020-09-28 17:48 UTC, yulllll commented on js/setup.js
> +  wizardElement.querySelector('.setup-similar-label').textContent = `${WIZARD_NAMES[i]} ${WIZARD_SURNAME[i]}`;
переменная `i` отсутствует в области видимости функции renderWizard

2020-09-28 17:48 UTC, yulllll commented on js/setup.js
> +for (var i = 0; i < wizards.length; i++) {
если нужно перебрать массив, то используй его метод forEach 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2020-09-29 10:57 UTC, yulllll requested changes

2020-09-29 10:57 UTC, yulllll commented on js/setup.js
> +const getRandomItem = function () {
elements сделай аргументом функции

2020-09-29 10:57 UTC, yulllll commented on js/setup.js
> +        WIZARD_NAMES[getRandomItem(WIZARD_NAMES.length)] +
getRandomItem(WIZARD_NAMES.length) -> getRandomItem(WIZARD_NAMES)

на вход функции должен идти массив из которого ты будешь выбирать случайный элемент

2020-09-29 10:57 UTC, yulllll commented on js/setup.js
> +  let elements = wizards;
wizards - это пустой массив, который ты наполняешь ниже в функции renderWizardsArr

2020-09-29 10:57 UTC, yulllll commented on js/setup.js
> +const getRandomItem = function () {
каждый раз при вызове функции на вход идет другой массив

2020-09-30 09:44 UTC, ministrov commented on js/setup.js
> +let similarListElement = document.querySelector('.setup-similar-list');
Тут просто не понял , прими пожалуйста задание , а это я исправлю в следующем)

2020-09-30 14:00 UTC, merged